### PR TITLE
Makefile fixes

### PR DESCRIPTION
**Pull request by 3x380V**
Just a bunch of Makefile cleanup. Apparently some duplicities could go into common included makefile. In that case it needs to be decided where that should reside.

### CODE REVIEW

**Comment by 3x380V** [comment]
With recent enough version of Lazarus, there is no need for Makefile magic to discover OS, target architecture, etc, instead `lazbuild --get-expand-text=...` can be used to query them...

**Comment by zamtmn** [comment]
> With recent enough version of Lazarus, there is no need for Makefile magic to discover OS, target architecture, etc, instead lazbuild --get-expand-text=... can be used to query them...

Yes, but it hasn't been added to the release(( as soon as it appears, we will implement

**Comment by zamtmn** [comment]
Thanks!

**Comment by 3x380V** [comment]
> Yes, but it hasn't been added to the release (as soon as it appears, we will implement)

That's primary reason why it is not part of this PR. I'll happily do it myself, just ping me once you move to newly released version.
Thank you for a quite useful software!

**Pull request merged**
